package main

import (
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
)
import "fmt"
import "mapreduce"

func inArray(arr []mapreduce.KeyValue, ele string)bool{
	if len(arr) == 0{
		return false
	}
	for _, word := range arr{
		if word.Key == ele{
			return true
		}

	}
	return false
}
// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Your code here (Part V).
	f := func(r rune)bool{
		return !unicode.IsLetter(r) && !unicode.IsNumber(r)
	}
	//https://golang.org/pkg/strings/#FieldsFunc
	//将满足string中满足f的去掉，并且以满足f的作为两个word之间的分割线
	words := strings.FieldsFunc(value, f)
	for _, word := range words{
		if !inArray(res, word){
			res = append(res, mapreduce.KeyValue{word, document})
		}
	}
	return
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Your code here (Part V).
	sort.Strings(values)
	res := strconv.Itoa(len(values))+" "+values[0]
	for i := 1; i < len(values); i++{
		res = res + "," + values[i]
	}
	return res
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("iiseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("iiseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
